"""empty message

Revision ID: 4b8f07f18700
Revises: 0d280df38d9c
Create Date: 2023-06-16 22:04:10.057136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8f07f18700'
down_revision = '0d280df38d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openai_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=1200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openai_logs', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
