"""empty message

Revision ID: 79d1bf54b070
Revises: 4b8f07f18700
Create Date: 2023-06-16 22:25:57.083551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d1bf54b070'
down_revision = '4b8f07f18700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['google_calendar_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_calendar_id')

    # ### end Alembic commands ###
